// <auto-generated/>
#pragma warning disable CS0618
using ArchiwindRevitAddIn.Api.Tokens.Caller;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ArchiwindRevitAddIn.Api.Tokens
{
    /// <summary>
    /// Builds and executes requests for operations under \tokens
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TokensRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The caller property</summary>
        public global::ArchiwindRevitAddIn.Api.Tokens.Caller.CallerRequestBuilder Caller
        {
            get => new global::ArchiwindRevitAddIn.Api.Tokens.Caller.CallerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Tokens.TokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokensRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tokens", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Tokens.TokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TokensRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tokens", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
