// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingPlan : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The detailed_credits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits? DetailedCredits { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits DetailedCredits { get; set; }
#endif
        /// <summary>The draft_credits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits? DraftCredits { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits DraftCredits { get; set; }
#endif
        /// <summary>The expires_on property</summary>
        public Date? ExpiresOn { get; set; }
        /// <summary>The name property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.BillingPlan_name? Name { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan"/> and sets the default values.
        /// </summary>
        public BillingPlan()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.BillingPlan CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.BillingPlan();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "detailed_credits", n => { DetailedCredits = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits>(global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits.CreateFromDiscriminatorValue); } },
                { "draft_credits", n => { DraftCredits = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits>(global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits.CreateFromDiscriminatorValue); } },
                { "expires_on", n => { ExpiresOn = n.GetDateValue(); } },
                { "name", n => { Name = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_name>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits>("detailed_credits", DetailedCredits);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits>("draft_credits", DraftCredits);
            writer.WriteDateValue("expires_on", ExpiresOn);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.BillingPlan_name>("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BillingPlan_detailed_credits : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_detailed_credits();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BillingPlan_draft_credits : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::ArchiwindRevitAddIn.Api.Models.BillingPlan.BillingPlan_draft_credits();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
