// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateModelFilesParamsV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The building property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_building? Building { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_building Building { get; set; }
#endif
        /// <summary>The surroundings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_surroundings? Surroundings { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_surroundings Surroundings { get; set; }
#endif
        /// <summary>The terrain property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_terrain? Terrain { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_terrain Terrain { get; set; }
#endif
        /// <summary>The vegetation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_vegetation>? Vegetation { get; set; }
#nullable restore
#else
        public List<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_vegetation> Vegetation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1"/> and sets the default values.
        /// </summary>
        public CreateModelFilesParamsV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "building", n => { Building = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_building>(global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_building.CreateFromDiscriminatorValue); } },
                { "surroundings", n => { Surroundings = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_surroundings>(global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_surroundings.CreateFromDiscriminatorValue); } },
                { "terrain", n => { Terrain = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_terrain>(global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_terrain.CreateFromDiscriminatorValue); } },
                { "vegetation", n => { Vegetation = n.GetCollectionOfObjectValues<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_vegetation>(global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_vegetation.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_building>("building", Building);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_surroundings>("surroundings", Surroundings);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_terrain>("terrain", Terrain);
            writer.WriteCollectionOfObjectValues<global::ArchiwindRevitAddIn.Api.Models.CreateModelFilesParamsV1_vegetation>("vegetation", Vegetation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
