// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListPageNav : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The current_offset property</summary>
        public int? CurrentOffset { get; set; }
        /// <summary>The current_page property</summary>
        public int? CurrentPage { get; set; }
        /// <summary>The limit property</summary>
        public int? Limit { get; set; }
        /// <summary>The next_offset property</summary>
        public int? NextOffset { get; set; }
        /// <summary>The next_page property</summary>
        public int? NextPage { get; set; }
        /// <summary>The previous_offset property</summary>
        public int? PreviousOffset { get; set; }
        /// <summary>The previous_page property</summary>
        public int? PreviousPage { get; set; }
        /// <summary>The total_count property</summary>
        public int? TotalCount { get; set; }
        /// <summary>The total_pages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.ListPageNav"/> and sets the default values.
        /// </summary>
        public ListPageNav()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.ListPageNav"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.ListPageNav CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.ListPageNav();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_offset", n => { CurrentOffset = n.GetIntValue(); } },
                { "current_page", n => { CurrentPage = n.GetIntValue(); } },
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "next_offset", n => { NextOffset = n.GetIntValue(); } },
                { "next_page", n => { NextPage = n.GetIntValue(); } },
                { "previous_offset", n => { PreviousOffset = n.GetIntValue(); } },
                { "previous_page", n => { PreviousPage = n.GetIntValue(); } },
                { "total_count", n => { TotalCount = n.GetIntValue(); } },
                { "total_pages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("current_offset", CurrentOffset);
            writer.WriteIntValue("current_page", CurrentPage);
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("next_offset", NextOffset);
            writer.WriteIntValue("next_page", NextPage);
            writer.WriteIntValue("previous_offset", PreviousOffset);
            writer.WriteIntValue("previous_page", PreviousPage);
            writer.WriteIntValue("total_count", TotalCount);
            writer.WriteIntValue("total_pages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
