// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SimulationStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "progress")]
        #pragma warning disable CS1591
        Progress,
        #pragma warning restore CS1591
        [EnumMember(Value = "success")]
        #pragma warning disable CS1591
        Success,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
    }
}
