// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SimulationV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The browser_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BrowserUrl { get; set; }
#nullable restore
#else
        public string BrowserUrl { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The expires_at property</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1? Params { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1 Params { get; set; }
#endif
        /// <summary>The project_id property</summary>
        public Guid? ProjectId { get; set; }
        /// <summary>The quality property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.SimulationQuality? Quality { get; set; }
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1? Results { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1 Results { get; set; }
#endif
        /// <summary>The share_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.SimulationV1_share_status? ShareStatus { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.SimulationV1_share_status ShareStatus { get; set; }
#endif
        /// <summary>The source property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.SimulationSource? Source { get; set; }
        /// <summary>The status property</summary>
        public global::ArchiwindRevitAddIn.Api.Models.SimulationStatus? Status { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationV1"/> and sets the default values.
        /// </summary>
        public SimulationV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.SimulationV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.SimulationV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "browser_url", n => { BrowserUrl = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "params", n => { Params = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1>(global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1.CreateFromDiscriminatorValue); } },
                { "project_id", n => { ProjectId = n.GetGuidValue(); } },
                { "quality", n => { Quality = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationQuality>(); } },
                { "results", n => { Results = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1>(global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1.CreateFromDiscriminatorValue); } },
                { "share_status", n => { ShareStatus = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationV1_share_status>(global::ArchiwindRevitAddIn.Api.Models.SimulationV1_share_status.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationSource>(); } },
                { "status", n => { Status = n.GetEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationStatus>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("browser_url", BrowserUrl);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1>("params", Params);
            writer.WriteGuidValue("project_id", ProjectId);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationQuality>("quality", Quality);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1>("results", Results);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationV1_share_status>("share_status", ShareStatus);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationSource>("source", Source);
            writer.WriteEnumValue<global::ArchiwindRevitAddIn.Api.Models.SimulationStatus>("status", Status);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
