// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SimulationResultsV1_attachments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The processed_images_expire_on property</summary>
        public Date? ProcessedImagesExpireOn { get; set; }
        /// <summary>The processed_images_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessedImagesUrl { get; set; }
#nullable restore
#else
        public string ProcessedImagesUrl { get; set; }
#endif
        /// <summary>The raw_data_expires_on property</summary>
        public Date? RawDataExpiresOn { get; set; }
        /// <summary>The raw_data_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawDataUrl { get; set; }
#nullable restore
#else
        public string RawDataUrl { get; set; }
#endif
        /// <summary>The report property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments_report? Report { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments_report Report { get; set; }
#endif
        /// <summary>The sampled_probes_expires_on property</summary>
        public Date? SampledProbesExpiresOn { get; set; }
        /// <summary>The sampled_probes_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SampledProbesUrl { get; set; }
#nullable restore
#else
        public string SampledProbesUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments"/> and sets the default values.
        /// </summary>
        public SimulationResultsV1_attachments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "processed_images_expire_on", n => { ProcessedImagesExpireOn = n.GetDateValue(); } },
                { "processed_images_url", n => { ProcessedImagesUrl = n.GetStringValue(); } },
                { "raw_data_expires_on", n => { RawDataExpiresOn = n.GetDateValue(); } },
                { "raw_data_url", n => { RawDataUrl = n.GetStringValue(); } },
                { "report", n => { Report = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments_report>(global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments_report.CreateFromDiscriminatorValue); } },
                { "sampled_probes_expires_on", n => { SampledProbesExpiresOn = n.GetDateValue(); } },
                { "sampled_probes_url", n => { SampledProbesUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("processed_images_expire_on", ProcessedImagesExpireOn);
            writer.WriteStringValue("processed_images_url", ProcessedImagesUrl);
            writer.WriteDateValue("raw_data_expires_on", RawDataExpiresOn);
            writer.WriteStringValue("raw_data_url", RawDataUrl);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.SimulationResultsV1_attachments_report>("report", Report);
            writer.WriteDateValue("sampled_probes_expires_on", SampledProbesExpiresOn);
            writer.WriteStringValue("sampled_probes_url", SampledProbesUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
