// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SimulationParamsV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>WGS84/EPSG:4326</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.Coordinates? Coords { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.Coordinates Coords { get; set; }
#endif
        /// <summary>The model_id property</summary>
        public Guid? ModelId { get; set; }
        /// <summary>in meters</summary>
        public double? Radius { get; set; }
        /// <summary>read more [here](https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset)</summary>
        public int? RefSystem { get; set; }
        /// <summary>The wind_directions property</summary>
        public int? WindDirections { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1"/> and sets the default values.
        /// </summary>
        public SimulationParamsV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.Models.SimulationParamsV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "coords", n => { Coords = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.Coordinates>(global::ArchiwindRevitAddIn.Api.Models.Coordinates.CreateFromDiscriminatorValue); } },
                { "model_id", n => { ModelId = n.GetGuidValue(); } },
                { "radius", n => { Radius = n.GetDoubleValue(); } },
                { "ref_system", n => { RefSystem = n.GetIntValue(); } },
                { "wind_directions", n => { WindDirections = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.Coordinates>("coords", Coords);
            writer.WriteGuidValue("model_id", ModelId);
            writer.WriteDoubleValue("radius", Radius);
            writer.WriteIntValue("ref_system", RefSystem);
            writer.WriteIntValue("wind_directions", WindDirections);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
