// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ArchiwindRevitAddIn.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WindCriteria
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "lawson_2001")]
        #pragma warning disable CS1591
        Lawson_2001,
        #pragma warning restore CS1591
        [EnumMember(Value = "lawson_lddc")]
        #pragma warning disable CS1591
        Lawson_lddc,
        #pragma warning restore CS1591
        [EnumMember(Value = "lawson_1978")]
        #pragma warning disable CS1591
        Lawson_1978,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_5281")]
        #pragma warning disable CS1591
        Is_5281,
        #pragma warning restore CS1591
    }
}
