<Project Sdk="Nice3point.Revit.Sdk/6.2.1">

    <PropertyGroup>
        <UseWPF>true</UseWPF>
        <UseWindowsForms Condition="$(RevitVersion) &lt; 2025">true</UseWindowsForms>
        <DeployAddin>true</DeployAddin>
        <LaunchRevit>true</LaunchRevit>
        <IsRepackable>false</IsRepackable>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Configurations>Debug.R23;Debug.R24;Debug.R25;Debug.R26;Debug.R27</Configurations>
        <Configurations>$(Configurations);Release.R23;Release.R24;Release.R25;Release.R26;Release.R27</Configurations>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Api\.kiota.log" />
      <None Remove="Resources\Icons\create-simulation-dark%4016.png" />
      <None Remove="Resources\Icons\create-simulation-dark%4032.png" />
      <None Remove="Resources\Icons\create-simulation-light%4016.png" />
      <None Remove="Resources\Icons\create-simulation-light%4032.png" />
      <None Remove="Resources\Icons\create-views-dark%4016.png" />
      <None Remove="Resources\Icons\create-views-dark%4032.png" />
      <None Remove="Resources\Icons\create-views-light%4016.png" />
      <None Remove="Resources\Icons\create-views-light%4032.png" />
      <None Remove="Resources\Icons\export-stls-dark%4016.png" />
      <None Remove="Resources\Icons\export-stls-dark%4032.png" />
      <None Remove="Resources\Icons\export-stls-light%4016.png" />
      <None Remove="Resources\Icons\export-stls-light%4032.png" />
      <None Remove="Resources\Icons\user-settings-dark%4016.png" />
      <None Remove="Resources\Icons\user-settings-dark%4032.png" />
      <None Remove="Resources\Icons\user-settings-light%4016.png" />
      <None Remove="Resources\Icons\user-settings-light%4032.png" />
      <None Remove="Resources\Images\logo.png" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="Resources\Icons\create-simulation-dark@16.png" />
      <Resource Include="Resources\Icons\create-simulation-dark@32.png" />
      <Resource Include="Resources\Icons\create-simulation-light@16.png" />
      <Resource Include="Resources\Icons\create-simulation-light@32.png" />
      <Resource Include="Resources\Icons\create-views-dark@16.png" />
      <Resource Include="Resources\Icons\create-views-dark@32.png" />
      <Resource Include="Resources\Icons\create-views-light@16.png" />
      <Resource Include="Resources\Icons\create-views-light@32.png" />
      <Resource Include="Resources\Icons\export-stls-dark@16.png" />
      <Resource Include="Resources\Icons\export-stls-dark@32.png" />
      <Resource Include="Resources\Icons\export-stls-light@16.png" />
      <Resource Include="Resources\Icons\export-stls-light@32.png" />
      <Resource Include="Resources\Icons\icon.ico" />
      <Resource Include="Resources\Icons\user-settings-dark@16.png" />
      <Resource Include="Resources\Icons\user-settings-dark@32.png" />
      <Resource Include="Resources\Icons\user-settings-light@16.png" />
      <Resource Include="Resources\Icons\user-settings-light@32.png" />
      <Resource Include="Resources\Images\logo.png" />
    </ItemGroup>

    <ItemGroup>
        <!-- Revit Dependencies -->
        <PackageReference Include="Nice3point.Revit.Toolkit" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Extensions" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" />
        <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" />

        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentValidation" Version="11.12.0" />
        <PackageReference Include="Microsoft.Kiota.Bundle" Version="1.22.1" />
        <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
        <PackageReference Condition="$(RevitVersion) &lt; 2025" Include="System.Security.Cryptography.ProtectedData" Version="10.0.5" />

        <!-- Development Dependencies -->
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="all" />
    </ItemGroup>

</Project>
