// <auto-generated/>
#pragma warning disable CS0618
using ArchiwindRevitAddIn.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ArchiwindRevitAddIn.Api.V1.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectsGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ArchiwindRevitAddIn.Api.Models.ProjectV1>? Items { get; set; }
#nullable restore
#else
        public List<global::ArchiwindRevitAddIn.Api.Models.ProjectV1> Items { get; set; }
#endif
        /// <summary>The nav property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ArchiwindRevitAddIn.Api.Models.ListPageNav? Nav { get; set; }
#nullable restore
#else
        public global::ArchiwindRevitAddIn.Api.Models.ListPageNav Nav { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsGetResponse"/> and sets the default values.
        /// </summary>
        public ProjectsGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ArchiwindRevitAddIn.Api.V1.Projects.ProjectsGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::ArchiwindRevitAddIn.Api.Models.ProjectV1>(global::ArchiwindRevitAddIn.Api.Models.ProjectV1.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nav", n => { Nav = n.GetObjectValue<global::ArchiwindRevitAddIn.Api.Models.ListPageNav>(global::ArchiwindRevitAddIn.Api.Models.ListPageNav.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ArchiwindRevitAddIn.Api.Models.ProjectV1>("items", Items);
            writer.WriteObjectValue<global::ArchiwindRevitAddIn.Api.Models.ListPageNav>("nav", Nav);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
